# Setup
title:               Huabaozi
tagline:             'A person who likes talking so much'
description:         'This blog is about study with some random thoughts as well.'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yumoku
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0

